In [13]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Lasso, LassoCV, LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import (GridSearchCV,cross_val_score,train_test_split)
from sklearn.preprocessing import StandardScaler

In [23]:
data = pd.read_csv('C:\\Users/andre/Downloads/winequality-white.csv')

In [34]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [9]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [27]:
y = data['quality']

In [29]:
X_train, X_holdout, y_train, y_holdout = train_test_split(data.drop('quality',axis=1),y,train_size=0.7,random_state=17)

In [31]:
X_train.shape

(3428, 11)

In [35]:
scaler = StandardScaler()

In [67]:
X_train_scaler = scaler.fit_transform(X_train)

In [68]:
X_holdout_scaler = scaler.transform(X_holdout)

In [39]:
linreg = LinearRegression()

In [69]:
linreg.fit(X_train_scaler,y_train)

LinearRegression()

In [48]:
linreg.predict(X_holdout)

array([5.57815637, 6.13413553, 5.93310004, ..., 6.93033664, 5.50467546,
       5.77599116])

In [70]:
mean_squared_error(y_train,linreg.predict(X_train_scaler))

0.5580606489803572

In [76]:
print(
    "Mean squared error (test): %.3f" %
    mean_squared_error(y_holdout,linreg.predict(X_holdout_scaler)))

Mean squared error (test): 0.584


In [78]:
linreg_coef = pd.DataFrame(
{
    "coef":linreg.coef_,
    "coef_abs":np.abs(linreg.coef_)
},index=data.columns.drop("quality"))

In [82]:
linreg_coef.sort_values(by='coef_abs',ascending=False)

coef  coef_abs
density              -0.665720  0.665720
residual sugar        0.538164  0.538164
volatile acidity     -0.192260  0.192260
pH                    0.150036  0.150036
alcohol               0.129533  0.129533
fixed acidity         0.097822  0.097822
sulphates             0.062053  0.062053
free sulfur dioxide   0.042180  0.042180
total sulfur dioxide  0.014304  0.014304
chlorides             0.008127  0.008127
citric acid          -0.000183  0.000183

In [85]:
linreg.coef_

array([ 9.78219223e-02, -1.92259947e-01, -1.83224449e-04,  5.38164096e-01,
        8.12724353e-03,  4.21804406e-02,  1.43040227e-02, -6.65720472e-01,
        1.50036006e-01,  6.20533605e-02,  1.29533447e-01])

In [86]:
np.abs(linreg.coef_)

array([9.78219223e-02, 1.92259947e-01, 1.83224449e-04, 5.38164096e-01,
       8.12724353e-03, 4.21804406e-02, 1.43040227e-02, 6.65720472e-01,
       1.50036006e-01, 6.20533605e-02, 1.29533447e-01])

In [87]:
linreg_coef

coef  coef_abs
fixed acidity         0.097822  0.097822
volatile acidity     -0.192260  0.192260
citric acid          -0.000183  0.000183
residual sugar        0.538164  0.538164
chlorides             0.008127  0.008127
free sulfur dioxide   0.042180  0.042180
total sulfur dioxide  0.014304  0.014304
density              -0.665720  0.665720
pH                    0.150036  0.150036
sulphates             0.062053  0.062053
alcohol               0.129533  0.129533

In [91]:
lasso1 = Lasso(alpha=0.01,random_state=17)

In [93]:
lasso1.fit(X_train_scaler,y_train)

Lasso(alpha=0.01, random_state=17)

In [96]:
lasso1_coef = pd.DataFrame({
    "coef":lasso1.coef_,
    "coef_abs":np.abs(lasso1.coef_)
},index = data.columns.drop('quality'))

In [101]:
lasso1_coef.sort_values(by='coef_abs',ascending=False)

coef  coef_abs
alcohol               0.322425  0.322425
residual sugar        0.256363  0.256363
density              -0.235492  0.235492
volatile acidity     -0.188479  0.188479
pH                    0.067277  0.067277
free sulfur dioxide   0.043088  0.043088
sulphates             0.029722  0.029722
chlorides            -0.002747  0.002747
fixed acidity        -0.000000  0.000000
citric acid          -0.000000  0.000000
total sulfur dioxide -0.000000  0.000000

In [102]:
alphas = np.logspace(-6,2,200)

In [105]:
lasso_cv = LassoCV(alphas=alphas,cv=5,random_state=17,n_jobs=-1)

In [106]:
%%time
lasso_cv.fit(X_train_scaler,y_train)

Wall time: 493 ms


LassoCV(alphas=array([1.00000000e-06, 1.09698580e-06, 1.20337784e-06, 1.32008840e-06,
       1.44811823e-06, 1.58856513e-06, 1.74263339e-06, 1.91164408e-06,
       2.09704640e-06, 2.30043012e-06, 2.52353917e-06, 2.76828663e-06,
       3.03677112e-06, 3.33129479e-06, 3.65438307e-06, 4.00880633e-06,
       4.39760361e-06, 4.82410870e-06, 5.29197874e-06, 5.80522552e-06,
       6.36824994e-06, 6.98587975e-0...
       1.18953407e+01, 1.30490198e+01, 1.43145894e+01, 1.57029012e+01,
       1.72258597e+01, 1.88965234e+01, 2.07292178e+01, 2.27396575e+01,
       2.49450814e+01, 2.73644000e+01, 3.00183581e+01, 3.29297126e+01,
       3.61234270e+01, 3.96268864e+01, 4.34701316e+01, 4.76861170e+01,
       5.23109931e+01, 5.73844165e+01, 6.29498899e+01, 6.90551352e+01,
       7.57525026e+01, 8.30994195e+01, 9.11588830e+01, 1.00000000e+02]),
        cv=5, n_jobs=-1, random_state=17)

In [110]:
lasso_cv.alpha_

0.0002833096101839324

In [112]:
lasso_cv_coef = pd.DataFrame({
    "coef":lasso_cv.coef_,
    "coef_abs":np.abs(lasso_cv.coef_)
},index = data.columns.drop('quality'))

In [113]:
lasso_cv_coef.sort_values(by='coef_abs')

coef  coef_abs
citric acid          -0.000000  0.000000
chlorides             0.006933  0.006933
total sulfur dioxide  0.012969  0.012969
free sulfur dioxide   0.042698  0.042698
sulphates             0.060939  0.060939
fixed acidity         0.093295  0.093295
alcohol               0.137115  0.137115
pH                    0.146549  0.146549
volatile acidity     -0.192049  0.192049
residual sugar        0.526883  0.526883
density              -0.648161  0.648161

In [119]:
print(
    "Mean squere error (train): %.3f"%
    mean_squared_error(y_train,lasso_cv.predict(X_train_scaler)))

Mean squere error (train): 0.558


In [116]:
mean_squared_error(y_holdout,lasso_cv.predict(X_holdout_scaler))

0.5832976077860635

In [159]:
forest = RandomForestRegressor(random_state=17)

In [165]:
forest.fit(X_train_scaler,y_train)

RandomForestRegressor(random_state=17)

In [166]:
print("Mean squared error (train): %.3f"
    % mean_squared_error(y_train,forest.predict(X_train_scaler)))

Mean squared error (train): 0.053


In [169]:
%%time
np.mean(np.abs(cross_val_score(forest,X_train_scaler,y_train,scoring='neg_mean_squared_error')))

Wall time: 5.52 s


0.4142003732204039

In [168]:
print("Mean squared error (test): %.3f" %
      mean_squared_error(y_holdout,forest.predict(X_holdout_scaler)))

Mean squared error (test): 0.372


In [184]:
params = {
    'max_depth':list(range(10,25)),
    'max_features':list(range(6,12))
}

In [204]:
locally_best_forest = GridSearchCV(RandomForestRegressor(n_jobs=-1, random_state=17),params,cv=5,n_jobs=-1,scoring='neg_mean_squared_error', verbose=True)

In [205]:
%%time
locally_best_forest.fit(X_train_scaler,y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits
Wall time: 2min 41s


GridSearchCV(cv=5, estimator=RandomForestRegressor(n_jobs=-1, random_state=17),
             n_jobs=-1,
             param_grid={'max_depth': [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
                                       20, 21, 22, 23, 24],
                         'max_features': range(6, 12)},
             scoring='neg_mean_squared_error', verbose=True)

In [192]:
%%time
locally_best_forest.fit(X_train_scaler,y_train)

Wall time: 2min 57s


GridSearchCV(cv=5, estimator=RandomForestRegressor(n_jobs=-1, random_state=17),
             n_jobs=-1,
             param_grid={'max_depth': [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
                                       20, 21, 22, 23, 24],
                         'max_features': range(6, 12)})

In [196]:
locally_best_forest.best_params_

{'max_depth': 21, 'max_features': 6}

In [139]:
locally_best_forest.best_params_

{'max_depth': 21, 'max_features': 6, 'min_samples_leaf': 1}

In [206]:
locally_best_forest.best_params_

{'max_depth': 21, 'max_features': 6}

In [207]:
locally_best_forest.best_score_

-0.39773288191505934

In [208]:
print("%.3f"%np.mean(np.abs(cross_val_score(locally_best_forest.best_estimator_,X_train_scaler,y_train,scoring='neg_mean_squared_error'))))

0.398


In [209]:
print("%.3f"%np.mean(mean_squared_error(y_holdout,locally_best_forest.best_estimator_.predict(X_holdout_scaler))))

0.366


In [210]:
rf_importance = pd.DataFrame({
    "coef":locally_best_forest.best_estimator_.feature_importances_
},index = data.columns.drop('quality'))

In [211]:
locally_best_forest.best_estimator_.feature_importances_

array([0.06181323, 0.11757796, 0.0626013 , 0.07207231, 0.07336551,
       0.11155573, 0.07363967, 0.08854909, 0.07365858, 0.05911054,
       0.20605608])

In [212]:
rf_importance.sort_values(by='coef')

coef
sulphates             0.059111
fixed acidity         0.061813
citric acid           0.062601
residual sugar        0.072072
chlorides             0.073366
total sulfur dioxide  0.073640
pH                    0.073659
density               0.088549
free sulfur dioxide   0.111556
volatile acidity      0.117578
alcohol               0.206056